'use strict';

function getKPI(tempExcel){
  //if(typeof require !== 'undefined') XLSX = require('xlsx');
  let XLSX;
  if(typeof require !== 'undefined') XLSX = require('xlsx');
  let workbook = XLSX.readFile(tempExcel);
  let first_sheet_name = workbook.SheetNames[21];
  let address_of_cell = 'C37';
  let worksheet = workbook.Sheets[first_sheet_name];
  let desired_cell = worksheet[address_of_cell];
  
  let safetyKpiJsonBase = { 
    "incident": [{"death":{"Jan":"chageme", "Feb":0, "Mar":0, "Apr":0, "May":0, "Jun":0, "Jul":0, "Aug":0, "Sep":0, "Oct":0, "Nov":0, "Dec":0},
	"lost_work_day":{"Jan":1, "Feb":1, "Mar":1, "Apr":1, "May":1, "Jun":1, "Jul":1, "Aug":1, "Sep":1, "Oct":1, "Nov":1, "Dec":1},
	"injury_with_restrictions":{"Jan":2, "Feb":2, "Mar":2, "Apr":2, "May":2, "Jun":2, "Jul":2, "Aug":2, "Sep":2, "Oct":2, "Nov":2, "Dec":2},
	"recordable_incident":{"Jan":3, "Feb":3, "Mar":3, "Apr":3, "May":3, "Jun":3, "Jul":3, "Aug":3, "Sep":3, "Oct":3, "Nov":3, "Dec":3},
	"first_aid":{"Jan":2, "Feb":4, "Mar":4, "Apr":4, "May":4, "Jun":4, "Jul":4, "Aug":4, "Sep":4, "Oct":4, "Nov":4, "Dec":4},
	"near_miss":{"Jan":5, "Feb":5, "Mar":5, "Apr":5, "May":5, "Jun":5, "Jul":5, "Aug":5, "Sep":5, "Oct":5, "Nov":5, "Dec":5},
	"unsafe_condition":{"Jan":6, "Feb":6, "Mar":6, "Apr":6, "May":6, "Jun":6, "Jul":6, "Aug":6, "Sep":6, "Oct":6, "Nov":6, "Dec":6},
	"unsafe_act":{"Jan":7, "Feb":7, "Mar":7, "Apr":7, "May":7, "Jun":7, "Jul":7, "Aug":7, "Sep":7, "Oct":7, "Nov":7, "Dec":7},
	"hours_worked":{"Jan":8, "Feb":8, "Mar":8, "Apr":8, "May":8, "Jun":8, "Jul":8, "Aug":8, "Sep":8, "Oct":8, "Nov":8, "Dec":8}
	}]
}
    //safetyKpiJsonBase.incident[0].death.Jan

  let sheet_name_list = workbook.SheetNames;

  sheet_name_list.forEach(function getSafetyKPI(tempSheetnames) { /* iterate through sheets */
    let worksheet = workbook.Sheets[tempSheetnames];
    let wantedPlant = "Warren";
    if(tempSheetnames===wantedPlant){
      for (let tempValueofCell in worksheet) {
      /* all keys that do not begin with "!" correspond to cell addresses */
        if(tempValueofCell[0] === '!') continue;
  //       console.log(worksheet[tempValueofCell].v);//must use v, can't change
       if((tempSheetnames==='Warren')&&(tempValueofCell==='C29'))
       {
           safetyKpiJsonBase.incident[0].death.Jan=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].death.Jan);
       }
       if((tempSheetnames==='Warren')&&(tempValueofCell==='D29'))
       {
           safetyKpiJsonBase.incident[0].death.Feb=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].death.Feb);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='E29'))
       {
           safetyKpiJsonBase.incident[0].death.Mar=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].death.Mar);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='F29'))
       {
           safetyKpiJsonBase.incident[0].death.Apr=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].death.Apr);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='G29'))
       {
           safetyKpiJsonBase.incident[0].death.May=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].death.May);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='H29'))
       {
           safetyKpiJsonBase.incident[0].death.Jun=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].death.Jun);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='I29'))
       {
           safetyKpiJsonBase.incident[0].death.Jul=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].death.Jul);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='J29'))
       {
           safetyKpiJsonBase.incident[0].death.Aug=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].death.Aug);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='K29'))
       {
           safetyKpiJsonBase.incident[0].death.Sep=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].death.Sep);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='L29'))
       {
           safetyKpiJsonBase.incident[0].death.Oct=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].death.Oct);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='M29'))
       {
           safetyKpiJsonBase.incident[0].death.Nov=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].death.Nov);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='N29'))
       {
           safetyKpiJsonBase.incident[0].death.Dec=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].death.Dec);
       }
///////////////////////////////////////////////////////////////////////
       if((tempSheetnames==='Warren')&&(tempValueofCell==='C30'))
       {
           safetyKpiJsonBase.incident[0].lost_work_day.Jan=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].lost_work_day.Jan);
       }
       if((tempSheetnames==='Warren')&&(tempValueofCell==='D30'))
       {
           safetyKpiJsonBase.incident[0].lost_work_day.Feb=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].lost_work_day.Feb);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='E30'))
       {
           safetyKpiJsonBase.incident[0].lost_work_day.Mar=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].lost_work_day.Mar);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='F30'))
       {
           safetyKpiJsonBase.incident[0].lost_work_day.Apr=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].lost_work_day.Apr);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='G30'))
       {
           safetyKpiJsonBase.incident[0].lost_work_day.May=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].lost_work_day.May);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='H30'))
       {
           safetyKpiJsonBase.incident[0].lost_work_day.Jun=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].lost_work_day.Jun);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='I30'))
       {
           safetyKpiJsonBase.incident[0].lost_work_day.Jul=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].lost_work_day.Jul);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='J30'))
       {
           safetyKpiJsonBase.incident[0].lost_work_day.Aug=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].lost_work_day.Aug);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='K30'))
       {
           safetyKpiJsonBase.incident[0].lost_work_day.Sep=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].lost_work_day.Sep);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='L30'))
       {
           safetyKpiJsonBase.incident[0].lost_work_day.Oct=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].lost_work_day.Oct);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='M30'))
       {
           safetyKpiJsonBase.incident[0].lost_work_day.Nov=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].lost_work_day.Nov);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='N30'))
       {
           safetyKpiJsonBase.incident[0].lost_work_day.Dec=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].lost_work_day.Dec);
       }
       //////////////////////////////////////////////////////////////////////////
              if((tempSheetnames==='Warren')&&(tempValueofCell==='C31'))
       {
           safetyKpiJsonBase.incident[0].injury_with_restrictions.Jan=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].injury_with_restrictions.Jan);
       }
       if((tempSheetnames==='Warren')&&(tempValueofCell==='D31'))
       {
           safetyKpiJsonBase.incident[0].injury_with_restrictions.Feb=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].injury_with_restrictions.Feb);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='E31'))
       {
           safetyKpiJsonBase.incident[0].injury_with_restrictions.Mar=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].injury_with_restrictions.Mar);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='F31'))
       {
           safetyKpiJsonBase.incident[0].injury_with_restrictions.Apr=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].injury_with_restrictions.Apr);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='G31'))
       {
           safetyKpiJsonBase.incident[0].injury_with_restrictions.May=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].injury_with_restrictions.May);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='H31'))
       {
           safetyKpiJsonBase.incident[0].injury_with_restrictions.Jun=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].injury_with_restrictions.Jun);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='I31'))
       {
           safetyKpiJsonBase.incident[0].injury_with_restrictions.Jul=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].injury_with_restrictions.Jul);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='J31'))
       {
           safetyKpiJsonBase.incident[0].injury_with_restrictions.Aug=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].injury_with_restrictions.Aug);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='K31'))
       {
           safetyKpiJsonBase.incident[0].injury_with_restrictions.Sep=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].injury_with_restrictions.Sep);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='L31'))
       {
           safetyKpiJsonBase.incident[0].injury_with_restrictions.Oct=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].injury_with_restrictions.Oct);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='M31'))
       {
           safetyKpiJsonBase.incident[0].injury_with_restrictions.Nov=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].injury_with_restrictions.Nov);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='N31'))
       {
           safetyKpiJsonBase.incident[0].injury_with_restrictions.Dec=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].injury_with_restrictions.Dec);
       }
//////////////////////////////////////////////////////////////
  if((tempSheetnames==='Warren')&&(tempValueofCell==='C32'))
       {
           safetyKpiJsonBase.incident[0].recordable_incident.Jan=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].recordable_incident.Jan);
       }
       if((tempSheetnames==='Warren')&&(tempValueofCell==='D32'))
       {
           safetyKpiJsonBase.incident[0].recordable_incident.Feb=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].recordable_incident.Feb);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='E32'))
       {
           safetyKpiJsonBase.incident[0].recordable_incident.Mar=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].recordable_incident.Mar);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='F32'))
       {
           safetyKpiJsonBase.incident[0].recordable_incident.Apr=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].recordable_incident.Apr);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='G32'))
       {
           safetyKpiJsonBase.incident[0].recordable_incident.May=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].recordable_incident.May);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='H32'))
       {
           safetyKpiJsonBase.incident[0].recordable_incident.Jun=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].recordable_incident.Jun);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='I32'))
       {
           safetyKpiJsonBase.incident[0].recordable_incident.Jul=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].recordable_incident.Jul);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='J32'))
       {
           safetyKpiJsonBase.incident[0].recordable_incident.Aug=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].recordable_incident.Aug);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='K32'))
       {
           safetyKpiJsonBase.incident[0].recordable_incident.Sep=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].recordable_incident.Sep);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='L32'))
       {
           safetyKpiJsonBase.incident[0].recordable_incident.Oct=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].recordable_incident.Oct);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='M32'))
       {
           safetyKpiJsonBase.incident[0].recordable_incident.Nov=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].recordable_incident.Nov);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='N32'))
       {
           safetyKpiJsonBase.incident[0].recordable_incident.Dec=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].recordable_incident.Dec);
       }
       ////////////////////////////////////////
       if((tempSheetnames==='Warren')&&(tempValueofCell==='C33'))
       {
           safetyKpiJsonBase.incident[0].first_aid.Jan=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].first_aid.Jan);
       }
       if((tempSheetnames==='Warren')&&(tempValueofCell==='D33'))
       {
           safetyKpiJsonBase.incident[0].first_aid.Feb=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].first_aid.Feb);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='E33'))
       {
           safetyKpiJsonBase.incident[0].first_aid.Mar=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].first_aid.Mar);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='F33'))
       {
           safetyKpiJsonBase.incident[0].first_aid.Apr=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].first_aid.Apr);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='G33'))
       {
           safetyKpiJsonBase.incident[0].first_aid.May=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].first_aid.May);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='H33'))
       {
           safetyKpiJsonBase.incident[0].first_aid.Jun=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].first_aid.Jun);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='I33'))
       {
           safetyKpiJsonBase.incident[0].first_aid.Jul=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].first_aid.Jul);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='J33'))
       {
           safetyKpiJsonBase.incident[0].first_aid.Aug=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].first_aid.Aug);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='K33'))
       {
           safetyKpiJsonBase.incident[0].first_aid.Sep=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].first_aid.Sep);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='L33'))
       {
           safetyKpiJsonBase.incident[0].first_aid.Oct=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].first_aid.Oct);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='M33'))
       {
           safetyKpiJsonBase.incident[0].first_aid.Nov=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].first_aid.Nov);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='N33'))
       {
           safetyKpiJsonBase.incident[0].first_aid.Dec=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].first_aid.Dec);
       }
       ///////////////////////////////////////////////////////
              if((tempSheetnames==='Warren')&&(tempValueofCell==='C34'))
       {
           safetyKpiJsonBase.incident[0].near_miss.Jan=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].near_miss.Jan);
       }
       if((tempSheetnames==='Warren')&&(tempValueofCell==='D34'))
       {
           safetyKpiJsonBase.incident[0].near_miss.Feb=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].near_miss.Feb);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='E34'))
       {
           safetyKpiJsonBase.incident[0].near_miss.Mar=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].near_miss.Mar);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='F34'))
       {
           safetyKpiJsonBase.incident[0].near_miss.Apr=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].near_miss.Apr);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='G34'))
       {
           safetyKpiJsonBase.incident[0].near_miss.May=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].near_miss.May);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='H34'))
       {
           safetyKpiJsonBase.incident[0].near_miss.Jun=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].near_miss.Jun);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='I34'))
       {
           safetyKpiJsonBase.incident[0].near_miss.Jul=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].near_miss.Jul);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='J34'))
       {
           safetyKpiJsonBase.incident[0].near_miss.Aug=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].near_miss.Aug);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='K34'))
       {
           safetyKpiJsonBase.incident[0].near_miss.Sep=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].near_miss.Sep);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='L34'))
       {
           safetyKpiJsonBase.incident[0].near_miss.Oct=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].near_miss.Oct);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='M34'))
       {
           safetyKpiJsonBase.incident[0].near_miss.Nov=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].near_miss.Nov);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='N34'))
       {
           safetyKpiJsonBase.incident[0].near_miss.Dec=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].near_miss.Dec);
       }
       /////////////////////////////////////////////////////////////////
                     if((tempSheetnames==='Warren')&&(tempValueofCell==='C35'))
       {
           safetyKpiJsonBase.incident[0].unsafe_condition.Jan=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].unsafe_condition.Jan);
       }
       if((tempSheetnames==='Warren')&&(tempValueofCell==='D35'))
       {
           safetyKpiJsonBase.incident[0].unsafe_condition.Feb=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].unsafe_condition.Feb);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='E35'))
       {
           safetyKpiJsonBase.incident[0].unsafe_condition.Mar=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].unsafe_condition.Mar);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='F35'))
       {
           safetyKpiJsonBase.incident[0].unsafe_condition.Apr=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].unsafe_condition.Apr);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='G35'))
       {
           safetyKpiJsonBase.incident[0].unsafe_condition.May=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].unsafe_condition.May);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='H35'))
       {
           safetyKpiJsonBase.incident[0].unsafe_condition.Jun=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].unsafe_condition.Jun);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='I35'))
       {
           safetyKpiJsonBase.incident[0].unsafe_condition.Jul=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].unsafe_condition.Jul);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='J35'))
       {
           safetyKpiJsonBase.incident[0].unsafe_condition.Aug=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].unsafe_condition.Aug);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='K35'))
       {
           safetyKpiJsonBase.incident[0].unsafe_condition.Sep=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].unsafe_condition.Sep);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='L35'))
       {
           safetyKpiJsonBase.incident[0].unsafe_condition.Oct=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].unsafe_condition.Oct);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='M35'))
       {
           safetyKpiJsonBase.incident[0].unsafe_condition.Nov=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].unsafe_condition.Nov);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='N35'))
       {
           safetyKpiJsonBase.incident[0].unsafe_condition.Dec=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].unsafe_condition.Dec);
       }
       /////////////////////////////////////////////////
                       if((tempSheetnames==='Warren')&&(tempValueofCell==='C36'))
       {
           safetyKpiJsonBase.incident[0].unsafe_act.Jan=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].unsafe_act.Jan);
       }
       if((tempSheetnames==='Warren')&&(tempValueofCell==='D36'))
       {
           safetyKpiJsonBase.incident[0].unsafe_act.Feb=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].unsafe_act.Feb);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='E36'))
       {
           safetyKpiJsonBase.incident[0].unsafe_act.Mar=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].unsafe_act.Mar);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='F36'))
       {
           safetyKpiJsonBase.incident[0].unsafe_act.Apr=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].unsafe_act.Apr);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='G36'))
       {
           safetyKpiJsonBase.incident[0].unsafe_act.May=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].unsafe_act.May);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='H36'))
       {
           safetyKpiJsonBase.incident[0].unsafe_act.Jun=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].unsafe_act.Jun);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='I36'))
       {
           safetyKpiJsonBase.incident[0].unsafe_act.Jul=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].unsafe_act.Jul);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='J36'))
       {
           safetyKpiJsonBase.incident[0].unsafe_act.Aug=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].unsafe_act.Aug);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='K36'))
       {
           safetyKpiJsonBase.incident[0].unsafe_act.Sep=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].unsafe_act.Sep);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='L36'))
       {
           safetyKpiJsonBase.incident[0].unsafe_act.Oct=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].unsafe_act.Oct);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='M36'))
       {
           safetyKpiJsonBase.incident[0].unsafe_act.Nov=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].unsafe_act.Nov);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='N36'))
       {
           safetyKpiJsonBase.incident[0].unsafe_act.Dec=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].unsafe_act.Dec);
       }
       /////////////////////////////////////////
                      if((tempSheetnames==='Warren')&&(tempValueofCell==='C37'))
       {
           safetyKpiJsonBase.incident[0].hours_worked.Jan=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].hours_worked.Jan);
       }
       if((tempSheetnames==='Warren')&&(tempValueofCell==='D37'))
       {
           safetyKpiJsonBase.incident[0].hours_worked.Feb=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].hours_worked.Feb);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='E37'))
       {
           safetyKpiJsonBase.incident[0].hours_worked.Mar=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].hours_worked.Mar);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='F37'))
       {
           safetyKpiJsonBase.incident[0].hours_worked.Apr=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].hours_worked.Apr);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='G37'))
       {
           safetyKpiJsonBase.incident[0].hours_worked.May=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].hours_worked.May);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='H37'))
       {
           safetyKpiJsonBase.incident[0].hours_worked.Jun=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].hours_worked.Jun);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='I37'))
       {
           safetyKpiJsonBase.incident[0].hours_worked.Jul=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].hours_worked.Jul);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='J37'))
       {
           safetyKpiJsonBase.incident[0].hours_worked.Aug=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].hours_worked.Aug);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='K37'))
       {
           safetyKpiJsonBase.incident[0].hours_worked.Sep=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].hours_worked.Sep);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='L37'))
       {
           safetyKpiJsonBase.incident[0].hours_worked.Oct=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].hours_worked.Oct);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='M37'))
       {
           safetyKpiJsonBase.incident[0].hours_worked.Nov=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].hours_worked.Nov);
       }
              if((tempSheetnames==='Warren')&&(tempValueofCell==='N37'))
       {
           safetyKpiJsonBase.incident[0].hours_worked.Dec=worksheet[tempValueofCell].v;
           console.log(safetyKpiJsonBase.incident[0].hours_worked.Dec);
       }
      }
    }
    console.log("this is the type of "+typeof safetyKpiJsonBase);
    return safetyKpiJsonBase;
  });
}

let excelUsing = 'safetyTest.xlsx';
getKPI(excelUsing);
